include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - public_member_api_docs
    - always_use_package_imports

analyzer:
  errors:
    invalid_annotation_target: ignore
    implementation_imports: error
  plugins:
    - custom_lint
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
analysis_options:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.gr.dart'